name: node-dev-environment

services:
  node-dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: node-dev
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    volumes:
      - ..:/node-dev
      - node_modules:/node-dev/node_modules

volumes:
  node_modules:
